kafka:
  brokers:
    - 172.21.1.164:9092
    - 172.21.1.84:9092
    - 172.21.1.8:9092
  topic: test-asyd
  producer:
    sleep: 0
    instances: 5
  consumer:
    group_id: test-asyd
    instances: 10
    sleep: 0.5
